### ISSUE TITLE
Major mods of db model

### ISSUE THREAD

**Issue by areedv** [mong/db#1]
We need to discuss the model. Current state:
![image](https://user-images.githubusercontent.com/1522857/89505007-396c0400-d7c9-11ea-8577-282665834094.png)

**Comment by areedv** [comment]
As for "dekningsgrad" we might consider a standard prefix for indicator ids (ind_id), _e.g._ __dg_nakke__, __dg_norgast_tarm__ etc.

**Comment by areedv** [comment]
Simplification after today's discussion:
![image](https://user-images.githubusercontent.com/1522857/89529149-83b2ac80-d7ec-11ea-949e-069f0886b58a.png)

**Comment by areedv** [comment]
_unit_level_ now added to _data_ table:
![image](https://user-images.githubusercontent.com/1522857/89628225-4a397a00-d89c-11ea-8e23-a7ba5b87a58f.png)

**Comment by areedv** [comment]
removed _ind_dep_ tab, replaced by self reference to _id_ in _ind_:
![image](https://user-images.githubusercontent.com/1522857/89640843-b8883780-d8b0-11ea-94f7-a80b8a879872.png)

**Comment by arnfinn** [comment]
I guess we finished this one...
