### ISSUE TITLE
Kolonne med format i `ind`-tabell

### ISSUE THREAD

**Issue by arnfinn** [mong/db#5]
Vi må ha en kolonne som definerer format på indikatorer. Disse vil som regel være `,.0%`, som betyr prosent uten siffer etter komma.

For å løse diverse issues i `qmongjs`:
- https://github.com/mong/qmongjs/issues/303
- https://github.com/mong/qmongjs/issues/796
- https://github.com/mong/qmongjs/issues/874

**Comment by areedv** [comment]
Trenger vi et eget grensesnitt for dette eller skal vi vedlikeholde formatering sjøl (gjennom adminer)?

**Comment by arnfinn** [comment]
I første omgang kan vi gjøre dette sjøl gjennom adminer. På sikt burde vi nok åpne opp for at dette, og noen andre ting, kan endres gjennom grensesnittet.

**Comment by areedv** [comment]
Hvis vi benytter en `sprintf` tilnærming så burde kanskje benevningen (_e.g._ `%`) ha sitt eget felt? Det kan også hende dette kan utledes av eksisterende `type`-felt i indikatortabellen. Har @yte0 noen preferanser på implementering?

Ellers så vil behandling av desimaltegn være mest levedyktig gjennom locale-instillinger og ikke ved hardkoding av `,` eller `.`
