### ISSUE TITLE
Master password expired. Implement permanentLogin() method to make it permanent.

### ISSUE THREAD

**Issue by arnfinn** [mong/db#6]
Får en advarsel når jeg skal logge inn til db gjennom adminer:
> Master password expired. [Implement](https://www.adminer.org/en/extension/) permanentLogin() method to make it permanent.

![image](https://user-images.githubusercontent.com/136346/170200279-7a494b91-2d43-4134-980e-9e5b8a2fe081.png)

**Comment by areedv** [comment]
Årsak kan være at nettleser som fyller skjema med rare data og i så fall kan en løsning være å nullstille historien. Lukker inntil videre da
